development:
  adapter: postgresql
  encoding: unicode
  database: sumpoints_db_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sumpoints_db_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sumpoints_db_prod
  pool: 5
  host: localhost